import { db } from "@workspace/db";
import {
  reportsTable,
  panicAlertsTable,
  missingPersonsTable,
  usersTable,
  adSlotsTable,
} from "@workspace/db/schema";

// San Ramón, Chanchamayo, Junín — center: -11.1282, -75.3554
async function seed() {
  console.log("🌱 Starting seed for San Ramón, Chanchamayo...");

  await db.delete(adSlotsTable);
  await db.delete(missingPersonsTable);
  await db.delete(panicAlertsTable);
  await db.delete(reportsTable);
  await db.delete(usersTable);

  await db.insert(usersTable).values([
    { name: "Admin Radar", email: "admin@radarvecinal.pe", role: "admin", sector: "San Ramón Centro", district: "San Ramón", reportsCount: 0 },
    { name: "Rosa Huamán", email: "rosa@example.com", role: "user", sector: "San Ramón Centro", district: "San Ramón", reportsCount: 5 },
    { name: "Carlos Quispe", email: "carlos@example.com", role: "user", sector: "Pampa del Carmen", district: "San Ramón", reportsCount: 3 },
    { name: "Ana Tuesta", email: "ana@example.com", role: "moderator", sector: "San Luis", district: "San Ramón", reportsCount: 12 },
    { name: "Jorge Suárez", email: "jorge@example.com", role: "user", sector: "Los Ángeles", district: "San Ramón", reportsCount: 7 },
  ]);

  const now = new Date();
  const ts = (hoursAgo: number, minsAgo = 0) =>
    new Date(now.getTime() - hoursAgo * 3600000 - minsAgo * 60000);

  await db.insert(reportsTable).values([
    {
      title: "Asalto a mano armada en Jr. Tarma",
      description: "Dos sujetos en moto asaltaron a una señora que salía del banco. Se llevaron cartera y celular. Escaparon hacia la Carretera Central.",
      category: "robbery",
      urgency: "critical",
      status: "active",
      isAnonymous: false,
      latitude:  -11.1272,
      longitude: -75.3548,
      address: "Jr. Tarma cdra. 3, San Ramón Centro",
      sector: "San Ramón Centro",
      authorName: "Carlos Quispe",
      confirmedCount: 8,
      createdAt: ts(0, 25),
      updatedAt: ts(0, 25),
    },
    {
      title: "Actitud sospechosa en Plaza de Armas",
      description: "Grupo de 4 personas desconocidas merodeando a los transeúntes en la plaza, con mochilas grandes. Varios vecinos los reportaron.",
      category: "suspicious",
      urgency: "medium",
      status: "reviewing",
      isAnonymous: true,
      latitude:  -11.1280,
      longitude: -75.3553,
      address: "Plaza de Armas, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Vecino Anónimo",
      confirmedCount: 4,
      createdAt: ts(1, 10),
      updatedAt: ts(1, 10),
    },
    {
      title: "Pelea callejera en Jr. Progreso",
      description: "Enfrentamiento entre dos grupos de jóvenes. Se escucharon gritos y se rompieron vidrios de una tienda.",
      category: "fight",
      urgency: "high",
      status: "resolved",
      isAnonymous: false,
      latitude:  -11.1265,
      longitude: -75.3558,
      address: "Jr. Progreso cdra. 2, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Rosa Huamán",
      confirmedCount: 12,
      createdAt: ts(3),
      updatedAt: ts(2),
    },
    {
      title: "Corte de agua en Av. Circunvalación",
      description: "Sin agua hace 8 horas en toda la cuadra. EMAPA Chanchamayo no da información.",
      category: "water_cut",
      urgency: "medium",
      status: "active",
      isAnonymous: false,
      latitude:  -11.1310,
      longitude: -75.3572,
      address: "Av. Circunvalación cdra. 4, Pampa del Carmen",
      sector: "Pampa del Carmen",
      authorName: "Jorge Suárez",
      confirmedCount: 15,
      createdAt: ts(5),
      updatedAt: ts(5),
    },
    {
      title: "Basura acumulada en mercado",
      description: "La Municipalidad no recogió la basura del mercado central hace 3 días. Malos olores y ratas.",
      category: "garbage",
      urgency: "low",
      status: "active",
      isAnonymous: false,
      latitude:  -11.1291,
      longitude: -75.3549,
      address: "Mercado Central, Jr. Junín, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Ana Tuesta",
      confirmedCount: 7,
      createdAt: ts(6),
      updatedAt: ts(6),
    },
    {
      title: "Emergencia médica en Carretera Central",
      description: "Adulto mayor sufrió un desmayo en la vereda. Ambulancia tardó 25 minutos en llegar.",
      category: "medical_emergency",
      urgency: "critical",
      status: "resolved",
      isAnonymous: false,
      latitude:  -11.1285,
      longitude: -75.3535,
      address: "Carretera Central PE-22B, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Jorge Suárez",
      confirmedCount: 3,
      createdAt: ts(8),
      updatedAt: ts(7),
    },
    {
      title: "Ruidos molestos en fiesta de Los Ángeles",
      description: "Fiesta con música a todo volumen desde las 11pm. No respetan el descanso vecinal.",
      category: "noise",
      urgency: "low",
      status: "archived",
      isAnonymous: true,
      latitude:  -11.1298,
      longitude: -75.3562,
      address: "AA.HH. Los Ángeles, Calle 4, San Ramón",
      sector: "Los Ángeles",
      authorName: "Vecino Anónimo",
      confirmedCount: 6,
      createdAt: ts(18),
      updatedAt: ts(18),
    },
    {
      title: "Asalto en grifo de la Carretera Central",
      description: "Delincuentes asaltaron el grifo de madrugada. El cajero fue amenazado con arma blanca.",
      category: "robbery",
      urgency: "critical",
      status: "active",
      isAnonymous: false,
      latitude:  -11.1263,
      longitude: -75.3541,
      address: "Grifo Chanchamayo, Carretera Central PE-22B",
      sector: "San Ramón Centro",
      authorName: "Carlos Quispe",
      confirmedCount: 20,
      createdAt: ts(2),
      updatedAt: ts(2),
    },
    {
      title: "Comercio ilícito en Jr. Lima",
      description: "Venta de productos sin procedencia conocida frente al mercado. Varios vecinos reportan la situación.",
      category: "informal_commerce",
      urgency: "low",
      status: "reviewing",
      isAnonymous: true,
      latitude:  -11.1288,
      longitude: -75.3545,
      address: "Jr. Lima cdra. 2, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Vecino Anónimo",
      confirmedCount: 9,
      createdAt: ts(12),
      updatedAt: ts(12),
    },
    {
      title: "Incendio en vivienda de San Luis",
      description: "Se inició un incendio en el segundo piso de una vivienda. Bomberos voluntarios acudieron en 18 min.",
      category: "fire",
      urgency: "critical",
      status: "resolved",
      isAnonymous: false,
      latitude:  -11.1255,
      longitude: -75.3580,
      address: "Sector San Luis, Calle Los Pinos, San Ramón",
      sector: "San Luis",
      authorName: "Ana Tuesta",
      confirmedCount: 18,
      createdAt: ts(14),
      updatedAt: ts(12),
    },
    {
      title: "Menor acosado cerca del colegio",
      description: "Un escolar fue seguido por un adulto desconocido desde el colegio. La madre reportó el hecho a la PNP.",
      category: "suspicious",
      urgency: "high",
      status: "reviewing",
      isAnonymous: false,
      latitude:  -11.1260,
      longitude: -75.3546,
      address: "Av. Ramón Castilla, cerca del colegio, San Ramón",
      sector: "San Ramón Centro",
      authorName: "Rosa Huamán",
      confirmedCount: 2,
      createdAt: ts(20),
      updatedAt: ts(20),
    },
    {
      title: "Robo de moto en Pampa del Carmen",
      description: "Se llevaron una moto Honda Wave estacionada frente al domicilio. Las llaves quedaron puestas.",
      category: "robbery",
      urgency: "high",
      status: "active",
      isAnonymous: false,
      latitude:  -11.1318,
      longitude: -75.3568,
      address: "Pampa del Carmen, Calle 7, San Ramón",
      sector: "Pampa del Carmen",
      authorName: "Jorge Suárez",
      confirmedCount: 1,
      createdAt: ts(28),
      updatedAt: ts(28),
    },
  ]);

  await db.insert(panicAlertsTable).values([
    {
      type: "robbery",
      latitude:  -11.1272,
      longitude: -75.3548,
      address: "Jr. Tarma cdra. 3, San Ramón Centro",
      authorName: "Usuario Anónimo",
      sector: "San Ramón Centro",
      isActive: true,
      createdAt: ts(0, 30),
    },
    {
      type: "medical",
      latitude:  -11.1285,
      longitude: -75.3535,
      address: "Carretera Central PE-22B, San Ramón",
      authorName: "Ana Tuesta",
      sector: "San Ramón Centro",
      isActive: false,
      createdAt: ts(8),
    },
    {
      type: "fight",
      latitude:  -11.1265,
      longitude: -75.3558,
      address: "Jr. Progreso cdra. 2, San Ramón",
      authorName: "Carlos Quispe",
      sector: "San Ramón Centro",
      isActive: false,
      createdAt: ts(5),
    },
  ]);

  await db.insert(missingPersonsTable).values([
    {
      name: "Sebastián",
      age: 9,
      clothing: "Uniforme escolar azul con mochila roja, zapatillas blancas",
      photoUrl: null,
      lastSeenLatitude:  -11.1260,
      lastSeenLongitude: -75.3546,
      lastSeenAddress: "Colegio Chanchamayo, Av. Ramón Castilla, San Ramón",
      lastSeenAt: ts(4),
      contactInfo: "Mamá: 987-654-321",
      status: "active",
      reportedBy: "Rosa Huamán",
      createdAt: ts(4),
    },
  ]);

  await db.insert(adSlotsTable).values([
    {
      businessName: "Ferretería El Constructor",
      tagline: "Materiales de construcción y acabados — San Ramón",
      imageUrl: null,
      targetUrl: "https://example.com",
      isActive: true,
      sector: "San Ramón Centro",
    },
    {
      businessName: "Botica San Ramón",
      tagline: "Medicamentos al mejor precio. Delivery Chanchamayo",
      imageUrl: null,
      targetUrl: "https://example.com",
      isActive: true,
      sector: null,
    },
  ]);

  console.log("✅ Seed complete: San Ramón, Chanchamayo data loaded.");
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
