import { db } from "@workspace/db";
import { reportsTable, panicAlertsTable, missingPersonsTable, usersTable, adSlotsTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

const LAT = -11.1272, LNG = -75.3548;
const j = (v: number, r = 0.0025) => parseFloat((v + (Math.random() * 2 - 1) * r).toFixed(6));
const ts = (daysAgo: number, hrsAgo = 0) =>
  new Date(Date.now() - daysAgo * 86400000 - hrsAgo * 3600000);

export async function autoSeedIfEmpty() {
  try {
    const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(reportsTable);
    if (Number(count) >= 5) {
      logger.info({ count }, "DB already has reports — skipping auto-seed");
      return;
    }

    logger.info("DB is empty — auto-seeding 50 demo reports...");

    // ── Usuario administrador ────────────────────────────────────────────
    // Solo el admin se crea en seed. Usuarios reales se registran vía /api/auth/register
    await db.insert(usersTable).values([
      { name: "Admin Radar Vecinal", email: "cponce123.com@gmail.com", role: "admin" as const, sector: "San Ramón Centro", district: "San Ramón", reportsCount: 0 },
    ]).onConflictDoNothing();

    // ── 50 Reportes ────────────────────────────────────────────────────────
    const reports = [
      // Últimos 15 días (12)
      { title: "Asalto a mano armada en Jr. Tarma", description: "Dos sujetos en moto asaltaron a señora frente al banco BN. Se llevaron cartera y celular Samsung.", category: "robbery" as const, urgency: "critical" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Tarma cdra. 3 frente al Banco de la Nación", sector: "San Ramón Centro", authorName: "Carlos Quispe", contactPhone: "987-654-321", confirmedCount: 8, createdAt: ts(0, 1) },
      { title: "Grupo sospechoso merodeando el mercado", description: "Cuatro individuos desconocidos recorren el mercado central, siguen a compradores.", category: "suspicious" as const, urgency: "high" as const, status: "reviewing" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Mercado Central de San Ramón, Jr. Junín", sector: "San Ramón Centro", authorName: "Rosa Huamán Torres", contactPhone: "943-221-100", confirmedCount: 11, createdAt: ts(0, 3) },
      { title: "Prostíbulo clandestino en Jr. Lima", description: "Local sin licencia opera desde las 10pm. Se han visto menores de edad ingresando.", category: "prostitution" as const, urgency: "high" as const, status: "reviewing" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Jr. Lima cdra. 4, San Ramón", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 6, createdAt: ts(1, 2) },
      { title: "Pelea a la salida de cantina en Jr. Grau", description: "Riña entre 6 personas, botellazos y sillazos. Un herido con corte en la cabeza.", category: "fight" as const, urgency: "high" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Grau cdra. 1, San Ramón", sector: "San Ramón Centro", authorName: "Pedro Campos López", contactPhone: "976-334-889", confirmedCount: 14, createdAt: ts(2, 1) },
      { title: "Punto de venta de drogas frente a la Iglesia", description: "Grupo de jóvenes vende sustancias en motos viernes y sábados desde las 8pm.", category: "drug_point" as const, urgency: "high" as const, status: "active" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Pampa del Carmen, frente a Iglesia Evangélica", sector: "Pampa del Carmen", authorName: "Anónimo", contactPhone: null, confirmedCount: 17, createdAt: ts(3) },
      { title: "Bar sin licencia con música hasta el amanecer", description: "Cantina opera sin permiso hasta las 5am. Ebrios en la calle cada fin de semana.", category: "bar_trouble" as const, urgency: "medium" as const, status: "active" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Av. Circunvalación cdra. 4, Pampa del Carmen", sector: "Pampa del Carmen", authorName: "Anónimo", contactPhone: null, confirmedCount: 9, createdAt: ts(4, 8) },
      { title: "Robo de moto Honda Wave en la noche", description: "Honda Wave roja, placa 3847-K, robada frente a mi casa. Dos sujetos captados en cámara.", category: "robbery" as const, urgency: "high" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Pampa del Carmen, Calle 7 Mz. D Lt. 3", sector: "Pampa del Carmen", authorName: "Jorge Suárez Rengifo", contactPhone: "989-002-341", confirmedCount: 3, createdAt: ts(5) },
      { title: "Corte de agua sin previo aviso — 3er día", description: "Llevamos tres días sin agua. EMAPA no responde. Familias con niños afectadas.", category: "water_cut" as const, urgency: "medium" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Av. Circunvalación cdra. 5, entre Jr. Cusco y Jr. Puno", sector: "Pampa del Carmen", authorName: "María Flores Espinoza", contactPhone: "987-123-456", confirmedCount: 22, createdAt: ts(6, 7) },
      { title: "Incendio en vivienda de material noble — San Luis", description: "Incendio por cortocircuito. Bomberos tardaron 18 min. Familia de 4 sin hogar.", category: "fire" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Sector San Luis, Calle Los Pinos Mz. C Lt. 9", sector: "San Luis", authorName: "Ana Tuesta Valles", contactPhone: "943-558-712", confirmedCount: 25, createdAt: ts(7, 22) },
      { title: "Basura acumulada 4 días sin recojo", description: "El camión de limpieza no pasa desde hace 4 días. Ratas y mal olor.", category: "garbage" as const, urgency: "low" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Junín, frente al Mercado Central", sector: "San Ramón Centro", authorName: "Cecilia Ríos Mendoza", contactPhone: null, confirmedCount: 15, createdAt: ts(8, 5) },
      { title: "Menor seguido por adulto desconocido", description: "Escolar seguido por hombre adulto desde el colegio. Intentó que subiera a su auto.", category: "suspicious" as const, urgency: "critical" as const, status: "reviewing" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Ramón Castilla cdra. 6, San Ramón", sector: "San Ramón Centro", authorName: "Rosa Huamán Torres", contactPhone: "943-221-100", confirmedCount: 7, createdAt: ts(9, 14) },
      { title: "Comercio ambulatorio ilegal bloquea vía", description: "Vendedores sin permiso ocupan vereda y calzada en Jr. Tarma.", category: "informal_commerce" as const, urgency: "low" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Tarma cdra. 1 y 2, San Ramón Centro", sector: "San Ramón Centro", authorName: "Luis Enrique Asto", contactPhone: null, confirmedCount: 8, createdAt: ts(13, 9) },
      // Días 15-44 (18)
      { title: "Robo a vivienda en Jr. Bolívar", description: "Rompieron la luna trasera. Robaron televisor, laptop y efectivo entre las 3-6pm.", category: "robbery" as const, urgency: "high" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Bolívar cdra. 3, San Ramón", sector: "San Ramón Centro", authorName: "Luz Mery Palomino", contactPhone: "968-445-231", confirmedCount: 4, createdAt: ts(15, 6) },
      { title: "Persona desaparecida — adulto mayor con demencia", description: "Abuelo de 78 años, Alzheimer leve, ropa verde y sombrero. Desapareció al mercado.", category: "missing_person" as const, urgency: "critical" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Ayacucho cdra. 2 — rumbo al mercado", sector: "San Ramón Centro", authorName: "Norma Beatriz Paredes", contactPhone: "987-333-000", confirmedCount: 12, createdAt: ts(16, 10) },
      { title: "Asalto en grifo Carretera Central — madrugada", description: "Tres encapuchados asaltaron al cajero. Huyeron en camioneta oscura.", category: "robbery" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Grifo Los Ángeles, Carretera Central PE-22B km 94.5", sector: "San Ramón Centro", authorName: "Carlos Quispe", contactPhone: "987-654-321", confirmedCount: 19, createdAt: ts(17, 3) },
      { title: "Ruidos molestos — fiesta hasta las 5am", description: "Vecino en Jr. Puno organiza fiestas todos los sábados. 3 semanas sin dormir.", category: "noise" as const, urgency: "low" as const, status: "reviewing" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Puno cdra. 2 Mz. B, San Ramón", sector: "San Ramón Centro", authorName: "Gilberto Torres Cárdenas", contactPhone: null, confirmedCount: 14, createdAt: ts(18, 21) },
      { title: "Peleas entre pandillas en Pampa del Carmen", description: "Dos grupos con palos y piedras. Tres heridos, uno trasladado de emergencia.", category: "fight" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Pampa del Carmen, Calle Principal esquina Calle 3", sector: "Pampa del Carmen", authorName: "Pedro Campos López", contactPhone: "976-334-889", confirmedCount: 21, createdAt: ts(19, 23) },
      { title: "Vehículo sospechoso ronda el colegio", description: "Auto sin placa ronda el colegio en horario de salida. Ofrecen dinero a alumnos.", category: "suspicious" as const, urgency: "critical" as const, status: "reviewing" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Colegio Santa Rosa, Av. Ramón Castilla, San Ramón", sector: "San Ramón Centro", authorName: "Gloria Ccapa Quispe", contactPhone: "956-778-334", confirmedCount: 18, createdAt: ts(20, 15) },
      { title: "Punto de drogas en parque Los Ángeles", description: "Tráfico visible en el parque de noche. Familias con niños no pueden usarlo.", category: "drug_point" as const, urgency: "high" as const, status: "reviewing" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Parque AA.HH. Los Ángeles, Calle 6", sector: "Los Ángeles", authorName: "Anónimo", contactPhone: null, confirmedCount: 9, createdAt: ts(21) },
      { title: "Emergencia médica — adulto mayor con derrame", description: "Señor 72 años, probable derrame. Ambulancia tardó 28 minutos.", category: "medical_emergency" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Arequipa cdra. 3, San Ramón", sector: "San Ramón Centro", authorName: "Heráclito Roca Zevallos", contactPhone: "943-667-120", confirmedCount: 6, createdAt: ts(23, 11) },
      { title: "Intento de robo — sujeto con cuchillo", description: "Joven interceptado con cuchillo. Escapó corriendo. Delincuente huyó al mercado.", category: "robbery" as const, urgency: "high" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Libertad cdra. 2, San Ramón", sector: "San Ramón Centro", authorName: "Erick Mamani Torres", contactPhone: "969-001-445", confirmedCount: 5, createdAt: ts(25, 18) },
      { title: "Incendio de pastizales — margen del río Tarma", description: "Quema fuera de control cerca del río. Se acercó a viviendas. Posible incendio intencional.", category: "fire" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Margen izquierda del Río Tarma, frente a Jr. Salaverry", sector: "Río Tarma", authorName: "Fernando Chávez Panduro", contactPhone: "987-889-223", confirmedCount: 13, createdAt: ts(27, 14) },
      { title: "Pelea en cantina El Paraíso — botellazo", description: "Herido con corte profundo en el brazo. Discoteca sin personal de seguridad.", category: "fight" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Progreso cdra. 3, cerca de discoteca El Paraíso", sector: "San Ramón Centro", authorName: "Sandra Paucar Huanca", contactPhone: null, confirmedCount: 8, createdAt: ts(28, 22) },
      { title: "Robo a negocio — vitrina rota de madrugada", description: "Rompieron vitrina de librería. Cámaras municipales no graban de noche.", category: "robbery" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Av. Juan Santos Atahualpa cdra. 2", sector: "San Ramón Centro", authorName: "Dora Quispe Ccahuana", contactPhone: "987-334-556", confirmedCount: 11, createdAt: ts(30, 4) },
      { title: "Prostitución callejera en Jr. Salaverry", description: "Mujeres ejercen prostitución en la vía pública desde las 9pm frente a menores.", category: "prostitution" as const, urgency: "medium" as const, status: "reviewing" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Jr. Salaverry cdra. 1 y 2", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 7, createdAt: ts(32) },
      { title: "Robo de cable eléctrico — 2 cuadras sin luz", description: "Cortaron y robaron cable eléctrico. Familias 2 días sin electricidad.", category: "robbery" as const, urgency: "medium" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Loreto cdra. 1 y 2, San Ramón", sector: "San Ramón Centro", authorName: "Wilder Gutiérrez Soto", contactPhone: "943-112-887", confirmedCount: 9, createdAt: ts(35, 18) },
      { title: "Ruidos molestos — taller mecánico sin horario", description: "Taller trabaja hasta las 11pm y desde las 6am incluyendo domingos. Sin licencia.", category: "noise" as const, urgency: "low" as const, status: "active" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Cusco cdra. 3, San Ramón Centro", sector: "San Ramón Centro", authorName: "Isabel Meléndez Ruiz", contactPhone: null, confirmedCount: 10, createdAt: ts(38, 8) },
      { title: "Sospechosos intentaron abrir puerta de vivienda", description: "Dos sujetos intentaron forzar mi puerta a las 2am. Calle sin alumbrado. Cuarta vez.", category: "suspicious" as const, urgency: "high" as const, status: "reviewing" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. San Martín cdra. 4, San Ramón", sector: "San Ramón Centro", authorName: "Nelly Apaza Mamani", contactPhone: "987-009-123", confirmedCount: 6, createdAt: ts(40, 2) },
      { title: "Emergencia — niño con quemaduras graves", description: "Niño de 6 años volcó olla con agua hirviendo. Quemaduras en tórax y brazos.", category: "medical_emergency" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Los Ángeles, Calle 8 Mz. F Lt. 12", sector: "Los Ángeles", authorName: "Flor de María Ramos", contactPhone: "943-778-901", confirmedCount: 4, createdAt: ts(42, 16) },
      { title: "Bar clandestino en El Milagro — 4 quejas ignoradas", description: "Bar sin permiso hace 5 meses. 4 quejas a la municipalidad sin atender.", category: "bar_trouble" as const, urgency: "medium" as const, status: "reviewing" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Jr. El Milagro cdra. 2, esquina Calle Los Pioneros", sector: "El Milagro", authorName: "Anónimo", contactPhone: null, confirmedCount: 16, createdAt: ts(44, 20) },
      // Días 45-89 (20)
      { title: "Robo en local comercial — farmacia", description: "Ladrones llevaron medicamentos por S/ 5,000. Usaron llave falsa copiada días antes.", category: "robbery" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Av. Juan Santos Atahualpa cdra. 3", sector: "San Ramón Centro", authorName: "Rosario Capcha Quispe", contactPhone: "987-445-672", confirmedCount: 14, createdAt: ts(46, 3) },
      { title: "Punto de drogas en zona del aeródromo", description: "Vehículo en berma de la PE-22B vende drogas en moto entre 8pm y 1am.", category: "drug_point" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Carretera PE-22B km 93.5, frente al aeródromo", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 8, createdAt: ts(49) },
      { title: "Pelea callejera en Jr. Callao — heridos", description: "Enfrentamiento con objetos contundentes. Dos heridos en el centro de salud.", category: "fight" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Callao cdra. 2, San Ramón Centro", sector: "San Ramón Centro", authorName: "Alfredo Huamán Rodríguez", contactPhone: "968-223-001", confirmedCount: 10, createdAt: ts(51, 22) },
      { title: "Prostíbulo en Pampa del Carmen — 3er reporte", description: "Tercer reporte del mismo local. Continúa funcionando. Posible soborno a inspectores.", category: "prostitution" as const, urgency: "high" as const, status: "archived" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Pampa del Carmen, Calle Principal cdra. 4", sector: "Pampa del Carmen", authorName: "Anónimo", contactPhone: null, confirmedCount: 12, createdAt: ts(54) },
      { title: "Robo a mano armada — tienda de abarrotes", description: "Tres sujetos con pistola vaciaron caja. Llevaron S/ 1,200 y celular. Huyeron en moto.", category: "robbery" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Progreso cdra. 1, tienda La Merced", sector: "San Ramón Centro", authorName: "Donato Saavedra Quispe", contactPhone: "987-667-332", confirmedCount: 16, createdAt: ts(56, 21) },
      { title: "Basura y desmonte en terreno baldío — San Luis", description: "Personas descargan desmonte de noche. Terreno convertido en basurero informal.", category: "garbage" as const, urgency: "low" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Sector San Luis, Calle Los Cedros", sector: "San Luis", authorName: "Teresa Cóndor Paucar", contactPhone: null, confirmedCount: 7, createdAt: ts(58, 14) },
      { title: "Encuestadores falsos — posibles ladrones", description: "Dos sujetos van de casa en casa. Preguntan qué equipos tienen. Fotografían interiores.", category: "suspicious" as const, urgency: "high" as const, status: "archived" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Los Jardines, Calles 5 y 6, San Ramón", sector: "Los Jardines", authorName: "Bertha Osorio Poma", contactPhone: "943-990-112", confirmedCount: 9, createdAt: ts(60) },
      { title: "Inundación y corte de agua simultáneo", description: "Tubería rota inundó Jr. Ica mientras había corte. EMAPA respondió 4 días después.", category: "water_cut" as const, urgency: "medium" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Ica cdra. 1, San Ramón Centro", sector: "San Ramón Centro", authorName: "Cinthia López Sánchez", contactPhone: "987-221-009", confirmedCount: 11, createdAt: ts(62, 10) },
      { title: "Robo de cosecha de cacao — sector Miraflores", description: "Ladrones ingresaron de noche y cosecharon cacao por S/ 2,800. Cuarta vez.", category: "robbery" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Sector Miraflores, parcela 14", sector: "Miraflores", authorName: "Efraín Aquino Villanueva", contactPhone: "968-554-000", confirmedCount: 5, createdAt: ts(65, 7) },
      { title: "Bodega con mercadería sin procedencia", description: "Vende electrónicos sin factura, presumiblemente robados. También vende alcohol a menores.", category: "informal_commerce" as const, urgency: "medium" as const, status: "archived" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Jr. San Martín cdra. 2", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 6, createdAt: ts(67) },
      { title: "Karaoke clandestino hasta las 3am", description: "Opera sin permiso todos los días. La municipalidad retiró el permiso pero sigue abierto.", category: "noise" as const, urgency: "medium" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Callao cdra. 3, San Ramón", sector: "San Ramón Centro", authorName: "Maximino Gómez Palomino", contactPhone: null, confirmedCount: 13, createdAt: ts(70, 23) },
      { title: "Pelea en AA.HH. Nueva Esperanza — arma blanca", description: "Pelea por deuda. Uno sacó cuchillo. PNP intervino sin detenidos.", category: "fight" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "AA.HH. Nueva Esperanza, Calle 3", sector: "Nueva Esperanza", authorName: "Anónimo", contactPhone: null, confirmedCount: 4, createdAt: ts(72, 19) },
      { title: "Asalto a turistas — sector puente Tarma", description: "Pareja de turistas asaltada por tres en moto. Cámaras, mochilas y documentos robados.", category: "robbery" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Puente sobre el Río Tarma, salida hacia La Merced", sector: "Río Tarma", authorName: "Roberto Chávez García", contactPhone: "943-667-889", confirmedCount: 20, createdAt: ts(74, 17) },
      { title: "Carne envenenada en parque — perros muertos", description: "Alguien puso carne envenenada. Tres perros murieron. Vecinos temen por niños.", category: "suspicious" as const, urgency: "high" as const, status: "archived" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Parque Los Jardines, Jr. Los Geranios", sector: "Los Jardines", authorName: "Milagros Chumpitaz Ayala", contactPhone: "987-772-334", confirmedCount: 9, createdAt: ts(76, 9) },
      { title: "Extorsión a comerciante del mercado", description: "Dueño de puesto recibe amenazas con cupo semanal de S/ 200. Ya pagó tres veces.", category: "robbery" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Mercado Central, puestos del lado norte", sector: "San Ramón Centro", authorName: "Giancarlo Trujillo Ortiz", contactPhone: "968-001-558", confirmedCount: 7, createdAt: ts(79, 11) },
      { title: "Incendio en depósito de madera — zona industrial", description: "Incendio destruyó depósito. Pérdidas de S/ 40,000. Dos compañías de bomberos.", category: "fire" as const, urgency: "critical" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Zona Industrial de San Ramón, salida a La Merced km 2", sector: "Zona Industrial", authorName: "Renato Arroyo Mendoza", contactPhone: "943-334-112", confirmedCount: 22, createdAt: ts(81, 4) },
      { title: "Accidente de tránsito — mototaxi volcado", description: "Mototaxi volcó por bache no señalizado. Conductor y dos pasajeros heridos.", category: "medical_emergency" as const, urgency: "high" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Av. Circunvalación cdra. 6, frente a grifo", sector: "Pampa del Carmen", authorName: "Paula Espinoza Tello", contactPhone: "987-009-667", confirmedCount: 8, createdAt: ts(84, 16) },
      { title: "Robo de herramientas en obra de construcción", description: "Robaron mezcladora, taladros y andamios. Pérdidas de S/ 8,000. Tres obreros sin trabajo.", category: "robbery" as const, urgency: "medium" as const, status: "resolved" as const, isAnonymous: false, latitude: j(LAT), longitude: j(LNG), address: "Jr. Bolívar cdra. 5, obra en construcción", sector: "San Ramón Centro", authorName: "Nancy Medina Soto", contactPhone: "987-443-221", confirmedCount: 6, createdAt: ts(86, 8) },
      { title: "Punto de tráfico de drogas — 2 meses documentado", description: "Durante 2 meses documentamos venta en esta esquina. Opera con vigilantes que avisan a la PNP.", category: "drug_point" as const, urgency: "critical" as const, status: "archived" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Esquina Jr. Junín con Jr. Ayacucho", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 23, createdAt: ts(88) },
      { title: "Bar problemático — 3 meses, 7 quejas ignoradas", description: "Bar sin habilitación hace 3 meses. 7 denuncias ignoradas. Peleas cada viernes. Exigimos cierre.", category: "bar_trouble" as const, urgency: "high" as const, status: "archived" as const, isAnonymous: true, latitude: j(LAT), longitude: j(LNG), address: "Jr. Junín cdra. 2, esquina Jr. Callao", sector: "San Ramón Centro", authorName: "Anónimo", contactPhone: null, confirmedCount: 28, createdAt: ts(89, 18) },
    ];

    await db.insert(reportsTable).values(reports.map(r => ({ ...r, updatedAt: r.createdAt })));

    // ── Panic Alerts ──────────────────────────────────────────────────────────
    await db.insert(panicAlertsTable).values([
      { type: "robbery" as const, latitude: j(LAT), longitude: j(LNG), address: "Jr. Tarma cdra. 3, San Ramón Centro", authorName: "Carlos Quispe", sector: "San Ramón Centro", isActive: true, createdAt: ts(0, 1) },
      { type: "medical" as const, latitude: j(LAT), longitude: j(LNG), address: "Carretera Central PE-22B, km 94", authorName: "Ana Tuesta", sector: "San Ramón Centro", isActive: false, createdAt: ts(0, 8) },
      { type: "fight" as const, latitude: j(LAT), longitude: j(LNG), address: "Jr. Grau cdra. 1, San Ramón", authorName: "Pedro Campos", sector: "San Ramón Centro", isActive: false, createdAt: ts(0, 5) },
    ]).onConflictDoNothing();

    // ── Missing Persons ───────────────────────────────────────────────────────
    await db.insert(missingPersonsTable).values([
      { name: "Sebastián Flores", age: 9, clothing: "Uniforme escolar azul, mochila roja, zapatillas blancas Nike", photoUrl: null, lastSeenLatitude: -11.1260, lastSeenLongitude: -75.3546, lastSeenAddress: "Colegio José Carlos Mariátegui, Av. Ramón Castilla", lastSeenAt: ts(0, 4), contactInfo: "Mamá Rosa: 987-654-321 | Papá Juan: 943-112-000", status: "active" as const, reportedBy: "Rosa Huamán Torres", createdAt: ts(0, 4) },
    ]).onConflictDoNothing();

    // ── Ad Slots ──────────────────────────────────────────────────────────────
    await db.insert(adSlotsTable).values([
      { businessName: "Ferretería El Constructor", tagline: "Materiales de construcción y acabados — San Ramón", imageUrl: null, targetUrl: "https://example.com", isActive: true, sector: "San Ramón Centro" },
      { businessName: "Botica San Ramón", tagline: "Medicamentos al mejor precio. Delivery en toda Chanchamayo", imageUrl: null, targetUrl: "https://example.com", isActive: true, sector: null },
      { businessName: "Hospedaje Río Tarma", tagline: "Habitaciones cómodas, wifi y desayuno — desde S/ 45", imageUrl: null, targetUrl: "https://example.com", isActive: true, sector: "San Ramón Centro" },
    ]).onConflictDoNothing();

    logger.info("✅ Auto-seed completo: 50 reportes + admin insertados.");
  } catch (err) {
    logger.error({ err }, "Auto-seed failed — continuing without demo data");
  }
}
