import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import reportsRouter from "./reports";
import alertsRouter from "./alerts";
import statsRouter from "./stats";
import activityRouter from "./activity";
import usersRouter from "./users";
import storageRouter from "./storage";
import districtsRouter from "./districts";
import categoriesRouter from "./categories";
import featuresRouter from "./features";
import civicEducationRouter from "./civicEducation";
import embedRouter from "./embed";
import reportsPdfRouter from "./reportsPdf";
import messagesRouter from "./messages";
import reniecRouter from "./reniec";
import clearDemoRouter from "./clearDemo";
import licensesRouter from "./licenses";
import adminRouter from "./admin";
import telegramRouter from "./telegram";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(reniecRouter);
router.use(reportsRouter);
router.use(alertsRouter);
router.use(statsRouter);
router.use(activityRouter);
router.use(usersRouter);
router.use(storageRouter);
router.use(districtsRouter);
router.use(categoriesRouter);
router.use(featuresRouter);
router.use(civicEducationRouter);
router.use(embedRouter);
router.use(reportsPdfRouter);
router.use(messagesRouter);
router.use(licensesRouter);
router.use(adminRouter);
router.use(telegramRouter);

export default router;
